import "./styles/globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

//import { AppProvider } from "./context/AppContext";
import { CreateUserProvider } from "./context/CreateUserContext";
import { AppProvider } from "./context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`flex min-h-screen flex-col items-center p-2 h-dvh bg-slate-50`}>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
